<?php
class Client{
	//安卓打包替换
	public static $androidFileReplace = array(
	    'app_name' => array(
				'replace' => '2',
				'file' => 'Clan/res/values/strings.xml',
				'search' => 'BigApp',
				'type' => '1',
		),
		'bbs_name' => array(
				'replace' => '5',
				'file' => 'Clan/res/values/strings_title.xml',
				'search' => 'BigApp',
				'type' => '1',
		),
		'channel_string' => array(
				'replace' => '9',
				'file' => 'Clan/res/values/strings_config.xml',
				'search' => 'CHANNEL',
				'type' => '1',
		),
		'channel_gradle' => array(
				'replace' => '9',
				'file' => 'Clan/build.gradle',
				'search' => 'channel',
				'type' => '1',
		),
		'sharesdk' => array(
				'replace' => '10',
				'file' => 'ShareSDK/assets/ShareSDK.xml',
				'search' => '07de6f113e7de2be9033dcffe59eecd6',
				'type' => '1',
		),
		'sharesdk_2' => array(
				'replace' => '10',
				'file' => 'Clan/res/values/strings_key.xml',
				'search' => 'd7a4854de9e1885605289d15d9611ef0',
				'type' => '1',
		),
		'sharesdk_3' => array(
				'replace' => '10',
				'file' => 'Clan/res/values/strings_key.xml',
				'search' => '00506baabfbc03bb98f7ac2aa344629a',
				'type' => '1',
		),
		'color_value' => array(
				'replace' => '11',
				'file' => 'Clan/res/values/colors.xml',
				'search' => '#ff325376',
				'type' => '1',
		),
		'application_id' => array(
				'replace' => '12',
				'file' => 'Clan/build.gradle',
				'search' => 'com.youzu.clan',
				'type' => '1',
		),
		'app_url' => array(
				'replace' => '13',
				'file' => 'ClanBase/src/com/youzu/clan/base/config/Url.java',
				'search' => 'http://192.168.180.23:8080/discuz/api/mobile/index.php',
				'type' => '1',
		),
		'share_icon' => array(
				'replace' => '14',
				'file' => 'Clan/res/values/strings_config.xml',
				'search' => 'http://www.discuz.net/static/image/common/logo.png',
				'type' => '1',
		),
		'change_versionname_string' => array(
				'replace' => '16',
				'file' => 'Clan/res/values/strings_config.xml',
				'search' => '1.0.0',
				'type' => '1',
		),
		'change_versionname_gradle' => array(
				'replace' => '16',
				'file' => 'Clan/build.gradle',
				'search' => '1.0.0',
				'type' => '1',
		),
		'debug_key_alias' => array(
				'replace' => '17',
				'file' => 'Clan/build.gradle',
				'search' => 'youyu.keystore',
				'type' => '1',
		),
		'debug_store_password' => array(
				'replace' => '18',
				'file' => 'Clan/build.gradle',
				'search' => '1422@youzu',
				'type' => '1',
		),
		'debug_key_password' => array(
				'replace' => '19',
				'file' => 'Clan/build.gradle',
				'search' => 'xiaoshun@youzu',
				'type' => '1',
		),
		'release_key_alias' => array(
				'replace' => '17',
				'file' => 'Clan/build.gradle',
				'search' => 'youyu.keystore',
				'type' => '1',
		),
		'release_store_password' => array(
				'replace' => '18',
				'file' => 'Clan/build.gradle',
				'search' => '1422@youzu',
				'type' => '1',
		),
		'release_key_password' => array(
				'replace' => '19',
				'file' => 'Clan/build.gradle',
				'search' => 'xiaoshun@youzu',
				'type' => '1',
		),
		'release_key_store_content' => array(
				'replace' => '21',
				'file' => 'Clan/youzu.keystore',
				'type' => '3',
		),
		'use_wechat' => array(
				'replace' => '22',
				'file' => 'Clan/res/values/strings_sharesdk.xml',
				'search' => 'use_wechat_ok',
				'type' => '1',
		),
		'wechat_appid_1' => array(
				'replace' => '23',
				'file' => 'ShareSDK/assets/ShareSDK.xml',
				'search' => 'wxb05003635a752c53',
				'type' => '1',
		),
		'wechat_appid_2' => array(
				'replace' => '23',
				'file' => 'ShareSDK/assets/ShareSDK.xml',
				'search' => 'wxb05003635a752c53',
				'type' => '1',
		),
		'wechat_appid_3' => array(
				'replace' => '23',
				'file' => 'ShareSDK/assets/ShareSDK.xml',
				'search' => 'wxb05003635a752c53',
				'type' => '1',
		),
		'wechat_app_secret_1' => array(
				'replace' => '24',
				'file' => 'ShareSDK/assets/ShareSDK.xml',
				'search' => '1bf2e7110a83d2b1d2ce71c11f18ca36',
				'type' => '1',
		),
		'wechat_app_secret_2' => array(
				'replace' => '24',
				'file' => 'ShareSDK/assets/ShareSDK.xml',
				'search' => '1bf2e7110a83d2b1d2ce71c11f18ca36',
				'type' => '1',
		),
		'wechat_app_secret_3' => array(
				'replace' => '24',
				'file' => 'ShareSDK/assets/ShareSDK.xml',
				'search' => '1bf2e7110a83d2b1d2ce71c11f18ca36',
				'type' => '1',
		),
		'use_qq' => array(
				'replace' => '25',
				'file' => 'Clan/res/values/strings_sharesdk.xml',
				'search' => 'use_qq_ok',
				'type' => '1',
		),
		'qq_appid_1' => array(
				'replace' => '26',
				'file' => 'ShareSDK/assets/ShareSDK.xml',
				'search' => '1104768684',
				'type' => '1',
		),
		'qq_appid_2' => array(
				'replace' => '26',
				'file' => 'ShareSDK/assets/ShareSDK.xml',
				'search' => '1104768684',
				'type' => '1',
		),
		'qq_appkey_1' => array(
				'replace' => '27',
				'file' => 'ShareSDK/assets/ShareSDK.xml',
				'search' => 'QBWUohHz82fpd55h',
				'type' => '1',
		),
		'qq_appkey_2' => array(
				'replace' => '27',
				'file' => 'ShareSDK/assets/ShareSDK.xml',
				'search' => 'QBWUohHz82fpd55h',
				'type' => '1',
		),
		'use_weibo' => array(
				'replace' => '28',
				'file' => 'Clan/res/values/strings_sharesdk.xml',
				'search' => 'use_weibo_ok',
				'type' => '1',
		),
		'sina_weibo_appkey' => array(
				'replace' => '29',
				'file' => 'ShareSDK/assets/ShareSDK.xml',
				'search' => '3552514107',
				'type' => '1',
		),
		'sina_weibo_app_secret' => array(
				'replace' => '30',
				'file' => 'ShareSDK/assets/ShareSDK.xml',
				'search' => 'b234a863f8cfb50e4ec7c47ca0babba9',
				'type' => '1',
		),
		'sina_weibo_redirect_url' => array(
				'replace' => '31',
				'file' => 'ShareSDK/assets/ShareSDK.xml',
				'search' => 'https://api.weibo.com/oauth2/default.html',
				'type' => '1',
		),
		'build_type' => array(
				'replace' => '32',
				'file' => 'Clan/res/values/strings_config.xml',
				'search' => 'RELEASE',
				'type' => '1',
		),
		'change_versioncode_gradle' => array(
				'replace' => '33',
				'file' => 'Clan/build.gradle',
				'search' => '8888',
				'type' => '1',
		),
		'change_versioncode_string' => array(
				'replace' => '33',
				'file' => 'Clan/res/values/strings_config.xml',
				'search' => '8888',
				'type' => '1',
		),
		'jpush_key' => array(
				'replace' => '34',
				'file' => 'Clan/build.gradle',
				'search' => 'b7bf5ec527d73136c7a0944c',
				'type' => '1',
		),
                'jpush_category' => array(
                                'replace' => '35',
                                'file' => 'Clan/AndroidManifest.xml',
                                'search' => '<category android:name="com.youzu.clan" />',
                                'type' => '1',
                ),
                'jpush_permission' => array(
                                'replace' => '36',
                                'file' => 'Clan/AndroidManifest.xml',
                                'search' => 'android:name="com.youzu.clan.permission.JPUSH_MESSAGE"',
                                'type' => '1',
                ),
		'drawable-hdpi' => array(
				'file' => 'Clan/res/drawable-hdpi/ic_launcher.png',
				'size' => '72_72',
				'type' => '2',
				'copy' => '3',
		),
		'drawable-ldpi' => array(
				'file' => 'Clan/res/drawable-ldpi/ic_launcher.png',
				'size' => '36_36',
				'type' => '2',
				'copy' => '3',
		),
		'drawable-mdpi' => array(
				'file' => 'Clan/res/drawable-mdpi/ic_launcher.png',
				'size' => '48_48',
				'type' => '2',
				'copy' => '3',
		),
		'drawable-xhdpi' => array(
				'file' => 'Clan/res/drawable-xhdpi/ic_launcher.png',
				'size' => '96_96',
				'type' => '2',
				'copy' => '3',
		),
		'drawable-xxhdpi' => array(
				'file' => 'Clan/res/drawable-xxhdpi/ic_launcher.png',
				'size' => '144_144',
				'type' => '2',
				'copy' => '3',
		),
		'drawable-xxhdpi_launch' => array(
				'file' => 'Clan/res/drawable-xxhdpi/splash.png',
				'size' => '1080_1920',
				'type' => '2',
				'copy' => '4',
		),
	);
	
}
?>
